### ISSUE TITLE
Peer to Peer Review

### ISSUE THREAD

**Issue by EzekielUtshudi** [Yazino12/awesome-books#5]

**Comment by EzekielUtshudi** [comment]
DRY, KISS, YAGNI, and JavaScript best practice review.
I checked your code against JavaScript best practices, YAGNI, KISS, and DRY, I'm glad that you wrote your code in a professional way 👍

You managed to keep your code simple, and separate files which made it simple and easy to understand 😄

You had managed to not repeat any block of code with the same functionality however you reused the code which made your code so awesome 👌

Nothing else to add to your repo, keep your movement on 🍾

**Comment by kosher9** [comment]
Hi @fahdrahali . Good job so far. You have done a good job.
After a good look at your project, @DanUshindi, @EzekielUtshudi, and I noticed that there are some changes you can make to make your website looks better:
- In your contact section we noticed that the content is not visible. Maybe you can change the color.
- In your navigation bar, maybe you can add some interaction to give users a better user experience.
